go_binary(
    name = 'rol-o-decks',
    srcs = [
        'main.go',
    ],
    deps = [
        '//indexer:indexer',
        '//server/handlers:handlers',
        '//store:store',
        '//third_party:gorilla_mux',
        '//ui:ui_bundle',
    ]
)