go_binary(
    name = 'main',
    srcs = [
        'main.go',
    ],
    deps = [
        '//third_party:gorilla_mux',
        '//server/handlers:handlers',
        '//store:store',
        '//ui/dist:ui_dist',
    ]
)