go_library(
    name = 'handlers',
    srcs = [
        'handlers.go',
    ],
    deps = [
        '//store:store',
        '//third_party:gorilla_mux',
    ],
    visibility = [
        '//cmd/main',
        '//indexer',
    ]
)