go_library(
    name = 'store',
    srcs = [
        'in_memory.go',
        'models.go',
        'store.go',
    ],
    visibility = [
        '//cmd/main',
        '//indexer',
        '//server/handlers',
    ]
)